name: htmx-examples-api
region: nyc
services:
- name: postgrest
  github:
    repo: your-github-username/scrape-embed
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.postgrest
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: PGHOST
    value: db-postgresql-nyc3-20256-do-user-18794323-0.k.db.ondigitalocean.com
    scope: RUN_TIME
  - key: PGPORT
    value: "25060"
    scope: RUN_TIME
  - key: PGDATABASE
    value: defaultdb
    scope: RUN_TIME
  - key: PGUSER
    value: web_anon
    scope: RUN_TIME
  - key: PGRST_DB_SCHEMA
    value: api
    scope: RUN_TIME
  - key: PGRST_DB_ANON_ROLE
    value: web_anon
    scope: RUN_TIME
  - key: PGRST_MAX_ROWS
    value: "100"
    scope: RUN_TIME
  - key: PGRST_DB_EXTRA_SEARCH_PATH
    value: public,openai
    scope: RUN_TIME 