version: '3'

services:
  postgrest:
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    environment:
      PGHOST: ${DB_HOST}
      PGPORT: ${DB_PORT}
      PGDATABASE: ${DB_NAME}
      PGUSER: ${POSTGREST_USER}
      PGPASSWORD: ${POSTGREST_PASSWORD}
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: ${POSTGREST_JWT_SECRET}
      PGRST_MAX_ROWS: 100
      PGRST_DB_EXTRA_SEARCH_PATH: public,openai
    restart: unless-stopped
    env_file:
      - .env 